# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'FoodWise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foodrama
  pod 'Moya'

  target 'FoodWiseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodWiseUITests' do
    # Pods for testing
  end

end
